FROM node:18-alpine

# Install Foundry dependencies
RUN apk add --no-cache bash curl git

# Install Foundry
RUN curl -L https://foundry.paradigm.xyz | bash
RUN /root/.foundry/bin/foundryup

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

WORKDIR /usr/src/app/xeon-contract

COPY xeon-contract/foundry.toml .

RUN /root/.foundry/bin/forge install

WORKDIR /usr/src/app

EXPOSE 3000

CMD ["npm", "run", "dev"]
