FROM node:18-alpine

# Install Foundry dependencies
RUN apk add --no-cache bash curl git

# Install Foundry
RUN curl -L https://foundry.paradigm.xyz | bash

# Manually add Foundry to the PATH
ENV PATH="/root/.foundry/bin:$PATH"

# Run foundryup to complete the installation
RUN foundryup

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

WORKDIR /app/xeon-contract

COPY xeon-contract/foundry.toml .

RUN forge install

WORKDIR /app

EXPOSE 3000

CMD ["npm", "run", "dev"]
